apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpadeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hpa
  template:
    metadata:
      name: hpapod
      labels:
        app: hpa
    spec:
      containers:
      - name: hpacontainer
        image: k8s.gcr.io/hpa-example
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            memory: "256Mi"
            cpu: "200m"
        ports:
        - containerPort: 80
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: hpasvc
spec:
  type: NodePort
  selector:
    app: hpa
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30004
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpadeploymentautoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hpadeployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 40
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 40
