apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebappdeployment
spec:
  selector:
    matchLabels:
      app: javawebapp
  template:
    metadata:
      labels:
        app: javawebapp
      name: javawebapppod
    spec:
      containers:
      - name: javawebappcontainer
        image: dockerhandson/java-web-app:1
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "400Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: javawebappsvc
spec:
  type: NodePort
  selector:
    app: javawebapp
  ports:
    
  - port: 80
    targetPort: 8080
