apiVersion: v1
kind: Pod
metadata: 
  name: javawebapppod
  labels:
    app: javawebapp
spec:
  containers:
  - name: javawebappcontainer
    image: dockerhandson/java-web-app:1  
    ports:
    - containerPort: 8080
  - name: nginxcontainer
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: javawebappsvc
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30002
    name: javacont
  - port: 80
    targetPort: 80
    nodePort: 30003
    name: nginxcont
  selector:
    app: javawebapp

