apiVersion: v1
kind: Namespace
metadata:
  name: devops-ns
  labels:
    team: devopsteam
    toolname: cicdtool
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkinsdeployment
  namespace: devops-ns
spec:
  selector:
    matchLabels:
      app: jenkinsapp
  template:
    metadata:
      labels:
        app: jenkinsapp
    spec:
      containers:
      - name: jenkinscontainer
        image: jenkins/jenkins:lts
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: jenkinsvol
          mountPath: /var/jenkins_home
      volumes:
      - name: jenkinsvol
        persistentVolumeClaim:
          claimName: jenkinspvc
        
          
---
apiVersion: v1
kind: Service
metadata:
  name: jenkinssvc
  namespace: devops-ns
spec:
  type: NodePort
  selector:
    app: jenkinsapp
  ports:
  - port: 80
    targetPort: 8080

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkinspvc
  namespace: devops-ns
spec:
  resources:
    requests:
      storage: 256Mi
  accessModes:
  - ReadWriteOnce

