apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongopv
  namespace: test-ns
spec:
  capacity:
    storage: 700Mi
  accessModes:
  - ReadWriteOnce
  nfs:
    server: 172.31.27.120
    path: /mnt/nfs_share
